### ISSUE TITLE
feat(Data):  There is only one Turbidity method and that method does not work for people who have no turbidity tubes.

### ISSUE THREAD

**Issue by irag** [BillionOysterProject/Digital-Platform#592]
This is an enhancement, but adding methods should improve the quality of the data.  A turbidity tube was used at the BOP training but one wasn't included in the kit and I didn't get one.  I measured turbidity either using a Secchi Disk or by how much of the rope was wet.  Since turbidity tube was the only available answer, I used it, even though it was incorrect.  I do not think that I'm the only BOP client that does not have a turbidity tube.

My BOP username is Ira Gershenhorn.

There is only one Turbidity method and that method does not work for people who have no turbidity tubes.

I do not know how the methods get into into the system.
I see there is a file in `scripts\mongo-load` called `metaTurbidityUnits.json` .  I don't know if that is edited directly or created from `metaTurbidityUnits.json`

If the latter, then I suggest, increasing the number of methods by increasing the number of lines in the csv.

In `metaTurbidityMethods.csv`
which currently has:
```
order,label,value
1,Turbidity tube,turbidityTube
```
Add 3 more methods:
```
2,Secchi Disk,Secchi Disk
3,Wet rope, Wet rope
4,Other,Other
```

**Comment by haflanagan** [comment]
@irag Adding additional water quality methods is _definitely_ a great idea, and it's something one of our middle school teachers recently requested as well.  Specifically, Clarissa Lynn at Central Park East II in Harlem requested a way to enter phosphates, fecal coliform, and additional methods for all of the existing water quality parameters.  This is unfortunately a more complicated feature request, since it involves adding database fields, a bunch more code in Angular (something I can't do myself), and rethinking the UI, but I would love to implement this.

This is something that would likely get addressed whenever we attempt a redesign of the data entry parts of the platform, so unfortunately it won't be soon.  (Since this is such core functionality on the platform, I would want to do much more user testing, get professional UX designers to take a look at it, and consider all of the other data entry-related feature requests from the community before redoing any of it.)  But this feedback is so helpful and I will definitely make sure this specific functionality makes its way into any redesign!

**Comment by irag** [comment]
@haflanagan I was thinking something far simpler.  Currently, the dropdown for turbidity method (not water quality method) only allows one choice, so probably everyone lies.  I lie.  I don't have a turbidity tube.  I'm only suggesting adding more choices for the way the turbidity is measured.  I am not suggesting more water quality methods.

**Comment by haflanagan** [comment]
@irag Ah, okay, although my points above still stand.  Adding more methods for turbidity is a good idea, but since it touches the database and requires changes to the Angular it's beyond what we can turn around quickly at the moment.

I think it's inaccurate to say that "everyone lies" about turbidity tubes, though- many teachers have turbidity tubes, and I believe that BOP included them in at least one version of the ORS setup.  I don't believe we've included turbidity tubes for a while, but that field is optional so you don't have to submit that data if you don't have a turbidity tube.  If you want to make one, there are a number of DIY turbidity tube tutorials online" https://mms-stream-study-wiki.wikispaces.com/file/view/turbidtube.pdf

For now, if you're really committed to submitting a turbidity measurement and you don't want to buy or build a turbidity tube, I'd use the secchi disk and just select the "turbidity tube" as the method for now.

**Comment by irag** [comment]
@haflanagan I don't know how you populate the drop downs. It seems and I could easily be wrong that you somehow modify the csv and run it through something and it becomes the Json file used in the system so the change may be as simple as modifying the csv and uploading it.  If that's true, I'd add a new choice, 5, ice ball, ice ball.  I realize some have turbidity tubes.  I don't know how many and I don't know what percent.  Not one of the 5 ORSs on the Baylander has one and I used a secchi disk until I lost it.  I haven't gotten around to making another.

**Comment by haflanagan** [comment]
@irag Unfortunately, based on exploring the files that control data entry before, I don't think it's as clear cut as that- it's definitely not as easy as just modifying a csv.  The methods are stored in the database, and then I believe there's something that changes the document in the Mongo database to JSON, and it's a bit beyond my ability to modify at this point.  But this will definitely find its way into a redesign, I promise!

**Comment by haflanagan** [comment]
Issue will be addressed with the redesign.
