### ISSUE TITLE
feat(Data): Append the Start Date and End Date labels with (YYYY-MM-DD) so users can just start entering a proper SQL date rather than wait for the date picker to popup.

### ISSUE THREAD

**Issue by irag** [BillionOysterProject/Digital-Platform#594]
This is an enhancement which will likely improve the perception of the platform.

My BOP username is Ira Gershenhorn.

Append the Start Date and End Date labels with (YYYY-MM-DD) so users can just start entering a proper SQL date rather than wait for the date picker to popup.

Currently, non-SQL formatted dates seem to be ignored.  I am recommending including the SQL format after the Start Date and End Date labels on the filter screen.  
This is how that screen looks now.
![image](https://user-images.githubusercontent.com/808169/34329674-4cefd1d4-e8d7-11e7-918c-2588b084a86a.png)

I am suggesting that we see Start Date (YYYY-MM-DD)  and End Date (YYYY-MM-DD)

In `modules\expeditions\client\views\filter-expeditions.client.view.html` ,
Line 17
Replace:
`<label class="control-label" for="startDate">Start Date</label>`
With:
`<label class="control-label" for="startDate (YYYY-MM-DD)">Start Date</label>`

and on
Line 32
Replace:
`<label class="control-label" for="endDate">End Date</label>`
With:
`<label class="control-label" for="endDate">End Date (YYYY-MM-DD)</label>`

If I could, I would label this as enhancement and help wanted.

**Comment by haflanagan** [comment]
@irag I just tested- the system currently *does* allow you to type in a date in its designated format (MM/DD/YYYY), but because the performance is slow (something I am hoping to remedy with a redesign) it might make it seem like it doesn't accept typed-in dates (thus forcing you to click the date-picker instead).  I agree that this is frustrating and needs improving and it will definitely be addressed in a redesign.

I'm inclined to keep the MM/DD/YYYY format since I suspect it's more familiar/intuitive to the students but I might be able to be persuaded to change it if lots of people felt strongly about changing the format.  

(As an unrelated aside, not that this affects the date format but we're not using a SQL database- we're fully in the world of NoSQL [using MongoDB].  I dream of a relational database one day, but for now referential integrity is just that- a dream.  Sigh.)

**Comment by irag** [comment]
Interesting about the database.  I just know from my experience with this cheap Actian Pervasive database I use that internally it requires that YYYY-MM-DD format, which seems to be standard.   I agree that MM/DD/YYYY is more familiar. While the software expects the YYYY-MM-DD format as input it outputs as MM/DD/YYYY.   The BOP software tests if anything has been entered but I believe that is the subject of another issue I created. I label my docs using YYYY-MMDD just so they alpha sort better.  I think the YMD format is generally called Swedish format.

**Comment by haflanagan** [comment]
@irag I had no idea it was called the Swedish format- the more you know!  I'm going to close out this issue for now but I'll keep it in mind when we get to a redesign.  Thanks again!
